# Generated by Django 3.2.10 on 2024-09-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='address_line_2',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash_courier', 'Наличными курьеру'), ('card_courier', 'Картой курьеру')], max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
